# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: TerraformBlueprint
metadata:
  name: terraform-google-filestore-lustre
  source:
    type: git
    repo: https://github.com/GoogleCloudPlatform/terraform-google-filestore-lustre.git
    # A subdirectory of the repo where the module is located
    # dir: /
  version: 1.0.0
  actuationTool:
    type: Terraform
    versions:
      - ">= 1.3.0"
  info:
    title: Filestore Lustre Instance
    description:
      tagline: Creates a Google Cloud Filestore Lustre instance.
      detailed: This module provisions a high-performance, parallel file system (Lustre) on Google Cloud Filestore, ideal for High-Performance Computing (HPC) workloads.
    icon: product-icons/filestore.svg
    documentation:
      - title: Google Cloud Filestore Lustre Documentation
        url: https://cloud.google.com/filestore/docs/lustre-fs
spec:
  terraformVariables:
    - name: name
      description: The resource name of the Lustre instance.
      type: string
      default: "lustre-instance-example"
      required: false
    - name: location
      description: The GCP zone where the instance will be created, e.g., `us-central1-a`.
      type: string
      default: "us-central1-a"
      required: true
    - name: network
      description: The full name of the VPC network to connect to, e.g. `projects/my-project/global/networks/my-network`.
      type: string
      default: "default"
      required: true
    - name: file_share_name
      description: The name of the file share being created. The name must be unique for the instance.
      type: string
      default: "lustre-share"
      required: false
    - name: capacity_gb
      description: The capacity of the file share in GiB. Must be at least 1200 (1.2 TiB) and a multiple of 1200.
      type: number
      default: 1200
      required: false
    - name: project_id
      description: The ID of the project in which the resource belongs. If it is not provided, the provider project is used.
      type: string
      required: true
    - name: description
      description: A description of the instance.
      type: string
      required: false
    - name: labels
      description: A set of key/value label pairs to apply to the instance.
      type: map
      default: {}
      required: false
    - name: kms_key_name
      description: The resource name of the customer-managed encryption key (CMEK) to use for the instance, e.g., `projects/my-project/locations/us-central1/keyRings/my-ring/cryptoKeys/my-key`. If not provided, Google-managed encryption will be used.
      type: string
      required: false
    - name: connect_mode
      description: The network connect mode of the Filestore instance. If not provided, DIRECT_PEERING will be used.
      type: string
      default: "DIRECT_PEERING"
      required: false
    - name: reserved_ip_range
      description: A /29 CIDR block in one of the allocated IP ranges. If not provided, a range will be automatically allocated.
      type: string
      required: false
    - name: network_modes
      description: IP versions for the instance. Lustre only supports MODE_IPV4.
      type: list
      default:
        - "MODE_IPV4"
      required: false
  terraformOutputs:
    - name: id
      description: The resource identifier of the Lustre instance.
    - name: name
      description: The name of the Lustre instance.
    - name: create_time
      description: The time when the instance was created.
    - name: ip_addresses
      description: The IP addresses of the instance. Clients will use these to connect.
    - name: instance
      description: The full Lustre instance resource object.
  requirements:
    services:
      - file.googleapis.com
      - compute.googleapis.com
      - cloudkms.googleapis.com
    roles:
      - level: project
        role: roles/file.editor
      - level: project
        role: roles/compute.networkUser
      - level: project
        role: roles/cloudkms.cryptoKeyEncrypterDecrypter
requirements:
  roles:
    - level: project
      role: roles/file.editor
    - level: project
      role: roles/iam.serviceAccountUser
